import os
from supabase import create_client, Client
from dotenv import load_dotenv

load_dotenv("../../web/.env")
url = os.environ.get("NEXT_PUBLIC_SUPABASE_URL")
key = os.environ.get("SUPABASE_SERVICE_ROLE_KEY") or os.environ.get("NEXT_PUBLIC_SUPABASE_ANON_KEY")

supabase: Client = create_client(url, key)

try:
    sql = """
    CREATE TABLE IF NOT EXISTS public.prompts_ia (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        nome TEXT NOT NULL,
        conteudo_prompt TEXT NOT NULL,
        is_ativo BOOLEAN DEFAULT false,
        created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
    );

    INSERT INTO public.prompts_ia (nome, conteudo_prompt, is_ativo)
    SELECT 'Prompt Padrão CAIXA', 'Faça uma análise hiperlocal de vendas do endereço do imóvel retornado na pesquisa, destacando o custo-benefício. Retorne estritamente o json e o texto de venda em HTML.', true
    WHERE NOT EXISTS (SELECT 1 FROM public.prompts_ia LIMIT 1);
    """
    
    # Executando via postgrest RPC se houver, mas como não temos, 
    # podemos usar uma query direta caso ele tenha rpc 'exec_sql'.
    # A DDL via Supabase API Data Client é limitada, então vamos ter que criar via NextJs migration ou instrução para criar no Studio.
    print("Por favor, crie a tabela via painel do Supabase se este script falhar: ")
    print(sql)
except Exception as e:
    print(e)
